// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIUfi3qVhL0Kx2Adu_iJdxU0pjMCofM2g',
    appId: '1:1030754800289:web:dee4aae77347a7200a56e0',
    messagingSenderId: '1030754800289',
    projectId: 'gym360-d9898',
    authDomain: 'gym360-d9898.firebaseapp.com',
    storageBucket: 'gym360-d9898.firebasestorage.app',
    measurementId: 'G-XVDN134WB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dmuitLKrqMzrqy3hZTiI9HXt4UCRacM',
    appId: '1:1030754800289:android:bc0902b7821038f40a56e0',
    messagingSenderId: '1030754800289',
    projectId: 'gym360-d9898',
    storageBucket: 'gym360-d9898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ7YvjkMtI2r1bI9mpuGVJEyWJ4HtbZqw',
    appId: '1:1030754800289:ios:96c080f26543115a0a56e0',
    messagingSenderId: '1030754800289',
    projectId: 'gym360-d9898',
    storageBucket: 'gym360-d9898.firebasestorage.app',
    androidClientId:
        '1030754800289-brcqqs6p6gre2ajhn4hh11jpvp7ec14p.apps.googleusercontent.com',
    iosClientId:
        '1030754800289-kbalvai7m5njgo41po67dm8r2mpfrio5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ7YvjkMtI2r1bI9mpuGVJEyWJ4HtbZqw',
    appId: '1:1030754800289:ios:96c080f26543115a0a56e0',
    messagingSenderId: '1030754800289',
    projectId: 'gym360-d9898',
    storageBucket: 'gym360-d9898.firebasestorage.app',
    androidClientId:
        '1030754800289-brcqqs6p6gre2ajhn4hh11jpvp7ec14p.apps.googleusercontent.com',
    iosClientId:
        '1030754800289-kbalvai7m5njgo41po67dm8r2mpfrio5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIUfi3qVhL0Kx2Adu_iJdxU0pjMCofM2g',
    appId: '1:1030754800289:web:10d5f745fd5a35e30a56e0',
    messagingSenderId: '1030754800289',
    projectId: 'gym360-d9898',
    authDomain: 'gym360-d9898.firebaseapp.com',
    storageBucket: 'gym360-d9898.firebasestorage.app',
    measurementId: 'G-80SD51JFXG',
  );
}
